language: node_js
node_js:
 - '6.11'
 - '7.9'
 - '8.1'

before_install:
  - mysql -e 'CREATE DATABASE honeymorning'
  - mysql -e 'CREATE TABLE blog'
  - mysql -e 'CREATE TABLE movie'

script: npm test

after_script:
  - npm run coverage

service: 
  - mysql